#!/usr/bin/env bash

TERRA_ENV=""
TERRA_GUI_BRANCH=""

red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -b|--branch) TERRA_GUI_BRANCH="--branch $2"; shift ;;
        -e|--env) TERRA_ENV="--env $2"; shift ;;
        *) echo "${red}ERROR: unknown parameter \"$1\"${reset}"; exit 1 ;;
    esac
    shift
done

TERRA_GUI_PATH=/content/terra_gui
TERRA_GUI_ENV=$TERRA_GUI_PATH/.terra-gui.env

if [ ! -f "$TERRA_GUI_ENV" ]; then
  tc-init $TERRA_ENV $TERRA_GUI_BRANCH
fi

set -o allexport; source $TERRA_GUI_ENV; set +o allexport

echo "Для начала работы перейдите по следующей ссылке $TERRA_GUI_URL"
cd $TERRA_GUI_PATH || exit
make &> /dev/null
