#!/usr/bin/env bash

TERRA_GUI_PATH=/content/terra_gui
AUTH_ENV=$TERRA_GUI_PATH/.auth.env
AUTH_URL=http://terra.neural-university.ru/api/v1/login/
BRANCH=""

if [ -f "$AUTH_ENV" ]; then
  set -o allexport; source $AUTH_ENV; set +o allexport
fi

red=$(tput setaf 1)
reset=$(tput sgr0)

while [ "$1" != "" ]; do
  PARAM=$(echo $1 | awk -F= '{print $1}')
  VALUE=$(echo $1 | awk -F= '{print $2}')
  case $PARAM in
    -b | --branch)
      BRANCH="--branch $VALUE"
      ;;
    *)
      echo "${red}ERROR: unknown parameter \"$PARAM\"${reset}"
      exit 1
      ;;
  esac
  shift
done

rm -rf $TERRA_GUI_PATH
git clone $BRANCH https://github.com/aiuniver/terra_gui.git $TERRA_GUI_PATH &> /dev/null
cd $TERRA_GUI_PATH || exit

terra_colab_gdmount

while [ -z "$AUTH_EMAIL" ]; do
  read -p "Введите E-mail: " AUTH_EMAIL
done

while [ -z "$AUTH_TOKEN" ]; do
  read -s -p "Введите Token: " AUTH_TOKEN
  echo ""
done

RESPONSE=$(terra_colab_auth --email=$AUTH_EMAIL --token=$AUTH_TOKEN --url=$AUTH_URL)
if [ -z "$RESPONSE" ]; then
  cat <<EOT >> $AUTH_ENV
AUTH_EMAIL=$AUTH_EMAIL
AUTH_TOKEN=$AUTH_TOKEN
EOT
  PATH=$TERRA_GUI_PATH:$PATH
else
  rm $AUTH_ENV
  echo "${red}$RESPONSE${reset}"
fi
