#!/usr/bin/env bash

TERRA_GUI_PATH=/content/terra_gui

if [ -f "$AUTH_ENV" ]; then
  set -o allexport; source $AUTH_ENV; set +o allexport
else
  terra_colab_init
fi

cd $TERRA_GUI_PATH || exit
make &> /dev/null
