#!/usr/bin/env bash

export AUTH_EMAIL
export AUTH_TOKEN

TERRA_GUI_PATH=/content/terra_gui
AUTH_URL=http://terra.neural-university.ru/api/v1/login/
BRANCH=""

red=$(tput setaf 1)
reset=$(tput sgr0)

function usage() {
  echo "Запуск web-сервиса"
  echo "!terra_colab_web [options]"
  echo "    -h, --help   - Данная справочная информация"
  echo "    -b, --branch - Имя ветки репозитория проекта TerraGUI на github.org"
  echo ""
}

while [ "$1" != "" ]; do
  PARAM=$(echo $1 | awk -F= '{print $1}')
  VALUE=$(echo $1 | awk -F= '{print $2}')
  case $PARAM in
    -h | --help)
      usage
      exit
      ;;
    -b | --branch)
      BRANCH="--branch $VALUE"
      ;;
    *)
      echo "${red}ERROR: unknown parameter \"$PARAM\"${reset}"
      echo ""
      usage
      exit 1
      ;;
  esac
  shift
done

terra_colab_gdmount

rm -rf $TERRA_GUI_PATH
git clone $BRANCH https://github.com/aiuniver/terra_gui.git $TERRA_GUI_PATH &> /dev/null
cd $TERRA_GUI_PATH || exit

if [[ -z "$AUTH_EMAIL" || -z "$AUTH_TOKEN" ]]; then
  read -p "Введите E-mail: " AUTH_EMAIL
  read -p "Введите Token: " AUTH_TOKEN
fi

RESPONSE=$(terra_colab_auth --email=$AUTH_EMAIL --token=$AUTH_TOKEN --url=$AUTH_URL)
if [ -z "$RESPONSE" ]; then
  make
else
  AUTH_EMAIL=""
  AUTH_TOKEN=""
  echo "${red}$RESPONSE${reset}"
fi
